[1620431824.045508] [1020] [II] Policy: reachability [ server ] -X-> [ r3 h1 fw h3 h2 s1 r1 r2 ]
[1620431824.787414] [1020] [II] EC: [ [192.168.0.254, 192.168.0.254] ]
[1620431824.787494] [1020] [II] dst_port: 80
[1620431824.787557] [1020] [EE] ***exec_step***
terminate called after throwing an instance of 'std::runtime_error'
  what():  ***exec_step***
